### ISSUE TITLE
Favicon showing on localhost but not gh-pages

### ISSUE THREAD

**Issue by jyuw** [CraftAcademy/CraftOverflow#12]
I've added a favicon to my site and it shows when I run the localhost, but not when deployed to Github Pages. 

#### Implementation code

```
    %link{href: "../assets/favicon.ico", rel: "icon", type: "image/x-icon"}/

```
Screenshot showing the favicon on the localhost (left) and the gh-pages (right)

![screen shot 2018-02-08 at 1 06 25 pm](https://user-images.githubusercontent.com/34248712/35972264-6c85182e-0cd1-11e8-8d51-8c9532f5cb2a.png)

### How did you try to solve the problem?
I tried putting the favicon in the root folder, source folder, and asset folder within the source folder, and it all works locally but not when deployed. 

I also tried
```
%link{href: "/favicon.ico?", rel: "icon", type: "image/x-icon"}/

and 

%link{href: "/favicon.ico?", rel: "icon"}/

and

%link{href: "../../favicon.ico?", rel: "icon"}/

```

**Comment by diraulo** [comment]
@jyuw 
Try using the `favicon_tag` helper as described [here](https://middlemanapp.com/basics/helper-methods/#asset-helpers)

```
<%= favicon_tag 'images/favicon.png' %>
```

**Comment by jyuw** [comment]
That worked thank you!
