### ISSUE TITLE
Wrong version of Ruby - Deploy to Netlify

### ISSUE THREAD

**Issue by davidboll** [CraftAcademy/CraftOverflow#13]
## Problem
I can't deploy to Netlify, I get an error saying wrong version of Ruby.

This is the error message;

``
11:39:03 AM: activesupport-5.0.6 requires ruby version >= 2.2.2, which is incompatible with
11:39:03 AM: the current version, ruby 2.1.2p95
11:39:03 AM: Error during gem install
11:39:03 AM: Build complete: exit code: 1
11:39:03 AM: Error running command: Build script returned non-zero exit code: 1
11:39:04 AM: Failing build: Failed to build site
11:39:04 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
11:39:04 AM: Finished processing build request in 14.575255971s``

In which file do I specify the ruby-version so that I can deploy?

**Comment by diraulo** [comment]
@davidboll Netlify currently supports the following ruby versions

```
2.0.0-p247
2.1.2
2.2.1
2.2.3
2.3.0
2.3.1
2.3.3
2.4.0
```

[More on that here](https://www.netlify.com/docs/#ruby)

create the `.ruby-version` file at the root of your application and specify the version you would like to use in there. In my demo, I made use of `2.3.1` but you can use any of the above

**Comment by davidboll** [comment]
Thank you Raoul! Works perfectly!
