### ISSUE TITLE
Editing site 

### ISSUE THREAD

**Issue by Fleurtam** [CraftAcademy/CraftOverflow#16]
Another question (homework was to post two so ;-) ) How do you edit and experiment on your site  without the results showing immediately on the actual website? Fork it and play around with the forked version?  Or is there a better way?

**Comment by tochman** [comment]
Just run it locally.

**Comment by Fleurtam** [comment]
Ha thanks! That local server didn't work earlier, but  following Holger's logic earlier to run middleman deploy, I ran middleman server. Now it all works fine!
