### ISSUE TITLE
No permission

### ISSUE THREAD

**Issue by OskarCA** [CraftAcademy/CraftOverflow#17]
Is this happening because I aslo recently been Invited to my works Github? 

Ideas? Trying to fork the fizzbuzz-js : https://github.com/CraftAcademy/fizzbuzz-js 

<img width="458" alt="screen shot 2018-02-11 at 17 44 34" src="https://user-images.githubusercontent.com/34236931/36075784-d519d2a6-0f53-11e8-808c-804d6ab69730.png">

**Comment by holgertidemand** [comment]
Just swap to your one account again?

**Comment by OskarCA** [comment]
@holgertidemand I'm on my usual account, and I am just an member of QUAD, I don't have an own account there.

**Comment by holgertidemand** [comment]
But you can swap between "accounts"

**Comment by OskarCA** [comment]
@holgertidemand Hmm will check It out.

**Comment by OskarCA** [comment]
Solution:  quit your job!

Jokes aside, not 100% sure why It was messing with me but leaved the 'quadorg' and It worked. If there Is anyone smart out there please feel free to just type something.

Thx!

**Comment by tochman** [comment]
The reason for `this` is that you already have it forked to your own repository. You can't fork a repo twice.

**Comment by OskarCA** [comment]
@tochman Okay boss! 😬
