### ISSUE TITLE
problem with installing Ruby 2.4.3

### ISSUE THREAD

**Issue by larathordar** [CraftAcademy/CraftOverflow#21]
![screen shot 2018-02-20 at 14 58 57](https://user-images.githubusercontent.com/31285696/36431325-93dfca06-1657-11e8-9f2d-a3ad445908ee.png)
When trying to install Ruby 2.4.3, which is required  in our challenge,  My terminal gives me an error message of 

```Error running '__rvm_make -j 1',
please read /Users/craftacademythree/.rvm/log/1519134914_ruby-2.4.3/make.log
There has been an error while running make. Halting the installation.
```

**Comment by diraulo** [comment]
@larathordar Can you please paste the content of that log file here?

you can run the following command to copy it's content and paste it here.. remember to format it 🙂 

```shell
pbcopy < /Users/craftacademythree/.rvm/log/1519134914_ruby-2.4.3/make.log
```

**Comment by larathordar** [comment]
[2018-02-20 14:57:33] __rvm_make
__rvm_make () 
{ 
    \make "$@" || return $?
}
current path: /Users/craftacademythree/.rvm/src/ruby-2.4.3
GEM_HOME=/Users/craftacademythree/.rvm/gems/ruby-2.4.1
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/craftacademythree/.rvm/gems/ruby-2.4.1/bin:/Users/craftacademythree/.rvm/gems/ruby-2.4.1@global/bin:/Users/craftacademythree/.rvm/rubies/ruby-2.4.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contenecho /Applications/Postgres.app/Contents/Versions/latest/bin:/Users/craftacademythree/.rvm/bin
GEM_PATH=/Users/craftacademythree/.rvm/gems/ruby-2.4.1:/Users/craftacademythree/.rvm/gems/ruby-2.4.1@global
command(3): __rvm_make -j 1
++ make -j 1
	CC = gcc
	LD = ld
	LDSHARED = gcc -dynamiclib
	CFLAGS = -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens   -fno-common -pipe 
	XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT
	CPPFLAGS = -I/usr/local/opt/libyaml/include -I/usr/local/opt/readline/include -I/usr/local/opt/libksba/include -I/usr/local/opt/openssl@1.1/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I.ext/include/x86_64-darwin15 -I./include -I. -I./enc/unicode/9.0.0
	DLDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl@1.1/lib -install_name /Users/craftacademythree/.rvm/rubies/ruby-2.4.3/lib/libruby.2.4.3.dylib -compatibility_version 2.4 -current_version 2.4.3  -fstack-protector -Wl,-u,_objc_msgSend -framework CoreFoundation  -fstack-protector -Wl,-u,_objc_msgSend -framework CoreFoundation  
	SOLIBS = -lpthread -lgmp -ldl -lobjc 
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
translating probes probes.d
error: error reading '/dev/fd/4'
1 error generated.
clang: error: unable to remove file: Permission denied
dtrace: failed to compile script probes.d: Preprocessor failed to process input program
make: *** [probes.h] Error 1
++ return 2
