### ISSUE TITLE
Travis setup

### ISSUE THREAD

**Issue by AntonellaMorittu** [CraftAcademy/CraftOverflow#22]
## Problem
Travis setup asks for admin rights

### Background
Setting Travis on rails_messaging_wookies returns this message:

You don't have sufficient rights to enable this repo on Travis. 
Please contact the admin to enable it or to receive admin rights yourself.

![schermata 2018-02-20 alle 15 51 52](https://user-images.githubusercontent.com/33493978/36430832-5d5df90e-1656-11e8-9228-54cd1735b629.png)

**Comment by diraulo** [comment]
@AntonellaMorittu  I Will fix the permissions for you on that repository

**Comment by diraulo** [comment]
You should be able to set that up now @AntonellaMorittu
