### ISSUE TITLE
Rspec error in cucumber tests... HELP

### ISSUE THREAD

**Issue by AKidd95** [CraftAcademy/CraftOverflow#23]
## Problem
Add associations between user with income and expenses. Breaks submit button for expenses and income.

### Background
* All tests were green before adding associations
* After added associations throws error (RSpec::Expectations::ExpectationNotMetError) when running Cucumber
* Submit button no longer works on any forms.

#### Spec
Please write a spec if any between the back ticks

```Income_spec.rb
RSpec.describe Income, type: :model do
  it { should have_db_column :amount}

  describe 'Associations' do
    it { should belong_to :user}
  end
end
```

```
describe 'Validations' do
    it { is_expected.to validate_presence_of :email }
  end

  describe 'Associations' do
    it {is_expected.to have_one :income}
    it {is_expected.to have_many :expenses}
  end
```

#### Implementation code
*schema file
```
  create_table "expenses", force: :cascade do |t|
    t.integer "rent"
    t.integer "insurance"
    t.integer "transportation"
    t.integer "education"
    t.integer "food"
    t.integer "other"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "leisure_activities"
    t.string "cultural_activities"
    t.string "holidays"
    t.string "sport"
    t.string "eating_out"
    t.string "beauty"
    t.string "various"
    t.integer "user_id"
  end

  create_table "incomes", force: :cascade do |t|
    t.integer "amount"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "user_id"
  end
```

### Screenshots
Add your screensh
![screen shot 2018-03-03 at 12 21 42 pm](https://user-images.githubusercontent.com/35339281/36933659-828abfac-1edd-11e8-893a-8cc6760b840b.png)
ots here

### How did you try to solve the problem?
Don't understand what the error could be. Initially thought it was a broken route. After it wasn't that I checked to see adding a user_id foreign key to income and expense tables would solve... it didn't.

**Comment by davidboll** [comment]
Do you have the text "Expense saved!" printed somewhere? Are you hitting the right page? You can always use a "Show me the page" to make sure.

**Comment by AKidd95** [comment]
We do have expense saved, but we are not hitting the correct page. Once we click submit nothing happens and we aren't redirected to the page that flashes "Expense saved!" which is why the tests are failing. All of tests were green before adding associations

**Comment by jyuw** [comment]
Is the form redirecting to the right path when you click create?

**Comment by AKidd95** [comment]
yes it redirects to our home_index_path which is where our "Expense save!" flash appears

**Comment by jyuw** [comment]
Maybe show us your code in the views?

**Comment by AKidd95** [comment]
![screen shot 2018-03-03 at 1 10 25 pm](https://user-images.githubusercontent.com/35339281/36934101-4c1e33e8-1ee4-11e8-9165-fdf9692762ce.png)
![screen shot 2018-03-03 at 1 10 12 pm](https://user-images.githubusercontent.com/35339281/36934102-4c3610f8-1ee4-11e8-973a-a995bd151ea8.png)
![screen shot 2018-03-03 at 1 09 59 pm](https://user-images.githubusercontent.com/35339281/36934103-4c4e9d8a-1ee4-11e8-8d57-93e97de147b5.png)
