### ISSUE TITLE
Setup Node on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by tochman** [CraftAcademy/CraftOverflow#28]
## Problem
One of the students (Robin Börjesson) is reporting: 

Are you aware of any previous students that have completed the prepcourse in the Windows Subsystem for Linux (WSL)? I installed it and set up the environment using your instructions for Ubuntu 16.4. Everything worked fine except for the installation of NodeJs. Googling the issue I found that others have hade the same problem and it could have something to do with the fact that I have NodeJs installed in my main environment aswell. I could tinker with it but if you know that this is not a good idea then please say so now and I will use the cloud version instead.

### Background
Refers to the setup instructions in the ITP course

**Comment by tochman** [comment]
@magnus-thor can you please take a look at this?

**Comment by magnus-thor** [comment]
![image](https://user-images.githubusercontent.com/26736754/43395296-d9145c44-93fd-11e8-853c-1ec5244ebbb0.png)

This is a permission issue. Run this command to verify `ls -alt ~/.zshrc` and the output should be similar to this `---------- 1 robin robin 181 Jul 30 11:10 /home/robin/.zshrc`. to fix this we need to run `sudo chmod 664 ~/.zshrc` and after that command we run `ls -alt ~/.zshrc` to verify its correctly set the output should be `-rw-rw-r-- 1 robin robin 181 Jul 30 11:10 /home/robin/.zshrc`
