### ISSUE TITLE
Custom message after Netlify's form is submitted

### ISSUE THREAD

**Issue by zanenkn** [CraftAcademy/CraftOverflow#37]
## Problem
Can not add a custom message after submitting the Netlify contact form

### Background
Working on React portfolio. Have added the Netlify contact form to the index.html (hidden) as well as made Contact.jsx. Have created Thankyou.jsx component that should be activated on submit of the form. I am calling on Thankyou.jsx as an action from the html (see implementation code) and it works on localhost but not when deployed. When form is submitted on the deployed site, it still shows Netlify's generic message. Deployed site [here](https://zanenkn.netlify.com/)

#### Implementation code
Thankyou.jsx
```js
import React from "react"

const Thankyou = () => {
    return (

        <div className="thanks-box">
            <p>Thank you for your message!</p>
        </div>      
    )                
}

export default Thankyou
```
index.html
```html
<body>

        <form name="contact" action="./Thankyou.jsx" netlify netlify-honeypot="bot-field" hidden>
            <input type="text" name="name" />
            <input type="email" name="email" />
            <textarea name="message"></textarea>
        </form>
        
        <div id="app"></div>

        <noscript>
            You need to enable JavaScript to run this React application.
        </noscript>
        
        <script src="dist/bundle.js"></script> 
    
    </body>
```

Repo [here](https://github.com/zanenkn/react_portfolio)

### How did you try to solve the problem?
Debugger didn't say anything helpful, it takes me to the bundle.js file that i dont really understand.

**Comment by zanenkn** [comment]
can i not say something along the lines
form action is `BrowserRouter` switch to `<Route exact path='/thankyou' component={Thankyou}></Route>` ?

**Comment by tochman** [comment]
I think you are getting around this from a perspective that is a dead end. I would suggest that you try to avoid mixing the "regular" way of adding a form with your React application. 

Start with taking a look at this package and read through the documentation. There is a perfectly fine example that you might want to tweak a bit to suit your needs.

https://www.npmjs.com/package/react-netlify-form

**Comment by zanenkn** [comment]
woaaaaaaahhhhhh it works!!!
(is it normal to get this emotional over nerdery?)

**Comment by tochman** [comment]
It is. It depends of course what “it” is...  what did you do?

**Comment by zanenkn** [comment]
1) installed react-netlify-form
2) defined the Contact component like this:
```js
const Contact = () => {
    return (
    <NetlifyForm name='contact'>
        {({ error, success }) => (
            <div>
                {error &&
                    <div>Your information was not sent. Please try again later.</div>
                }
                {success &&
                    <div>Thank you for your message!</div>
                }
                {!success &&
                    <div>
                        <input type='text' name='name' required />
                        <input type='email' name='email' required />
                        <textarea name='message' required />
                        <button>Submit</button>
                    </div>
                }
            </div>
        )}
    </NetlifyForm>
    )
}
```
