### ISSUE TITLE
Irb testing ATM-challenge: creating a new Person

### ISSUE THREAD

**Issue by piavW** [CraftAcademy/CraftOverflow#46]
## Problem
When in irb, we are unsuccessful at creating a new person. 

### Background
We can load all 3 .rb-files (atm, account, person), we can create a new ATM by writing atm.new
However when trying to create a new person of the Person-class no code works.
We've tried person = Person.new('name') and lots of variants of this. 

No one else in the cohort has been able to get past this so far. 

#### Story
- not relevant -

#### Implementation code
Please see github: https://github.com/piavW/atm_challenge_2019/commits/master

### Screenshots

<img width="1110" alt="Screenshot 2019-09-05 at 12 03 28" src="https://user-images.githubusercontent.com/53825385/64332641-31ae4900-cfd5-11e9-91b7-145e4a314ff7.png">

<img width="1033" alt="Screenshot 2019-09-05 at 12 02 48" src="https://user-images.githubusercontent.com/53825385/64332592-1e02e280-cfd5-11e9-91ea-fc9c8a98f2b7.png">

### How did you try to solve the problem?
We have checked course documentation, offical docs and others to find a guide or answer. We've asked our cohorts.

**Comment by faraznaeem** [comment]
try creating a person like this `person = Person.new({name: 'Faraz'})`

**Comment by piavW** [comment]
Thanks, that does the trick!

**Comment by piavW** [comment]
Can also be written without the curlybrackets as in 
```person = Person.new (name: 'Pia')```
