### ISSUE TITLE
Error: yarn run build (babel/core)

### ISSUE THREAD

**Issue by clalil** [CraftAcademy/CraftOverflow#47]
## Problem
We receive an error message in the terminal when running the command $ yarn run build. It mentions that it cannot find the module '@babel/core'.

### Background
Installing the webpack during the adress book challenge (https://learn.craftacademy.co/courses/650468/lectures/11624566).

### Screenshots
![Screen Shot 2019-09-10 at 09 50 09](https://user-images.githubusercontent.com/38570172/64600872-2a63b280-d3bc-11e9-9b95-8873bdf46ef1.png)

### How did you try to solve the problem?
We googled the error message, upon reading error message incredibly throughly - we managed to resolve this issue by adding:
babel-loader@7 using yarn.

**Comment by clalil** [comment]
Solves the problem:

$ yarn add babel-loader@7

**Comment by tochman** [comment]
In what context/project are youusing `yarn`?

**Comment by piavW** [comment]
This is for the address-book challenge Thomas so we use yarn and lots of other tools.
