### ISSUE TITLE
RSpec and HAML setup problem

### ISSUE THREAD

**Issue by davidboll** [CraftAcademy/CraftOverflow#5]
So, I can't get RSpec to work with the HAML-setup, I keep getting errors (see attachement) Do we need to require the “index.html.haml” in our “index_spec.rb”-file?

<img width="698" alt="skarmavbild 2018-02-05 kl 19 14 33" src="https://user-images.githubusercontent.com/25644242/35847284-4112c668-0b1a-11e8-80d3-266715eba897.png">

**Comment by tochman** [comment]
Please update your question with both the view (haml markup) and the spec.

**Comment by davidboll** [comment]
So, Raoul the wise gave me the solution, we need to add a line in our spec as seen below. The line we need to add is " visit '/' " (se line 3)

`describe 'Index Page', type: :feature do
  it 'displays project list' do
    visit '/'

    expect(page).to have_css '.projects'
    within '.projects' do
      expect(page).to have_content 'My First Website'
      expect(page).to have_content 'FizzBuzz'
    end
  end
end`

**Comment by diraulo** [comment]
@davidboll The reason why the `.projects` element was not found on the page in the test mode was because no page was actually visited in that context.

When writing features specs, as with all tests for that matter, you need a `Setup stage` where you execute an action first, then expect to have certain results.

In this case, the Setup involved _visiting the actual page_ we were running tests for.

**Comment by AntonellaMorittu** [comment]
@diraulo My “index_spec.rb”-file looks like this:

`describe 'Index Page', type: :feature do
  it 'displays project list' do
    visit '/'

    expect(page).to have_css '.projects'
    within '.projects' do
      
      expect(page).to have_content 'My First Website'
      expect(page).to have_content 'FizzBuzz'
    end
  end
end`

When I run Rspec, I still get this error message:

![schermata 2018-02-06 alle 10 33 02](https://user-images.githubusercontent.com/33493978/35851790-582eef48-0b29-11e8-9e5d-9ad9b8926e61.png)

Any ideas why?

**Comment by AntonellaMorittu** [comment]
Solved, I had the Data folder inside ./source, that caused the issue.
