### ISSUE TITLE
Portfolio challenge Rspec setup issue.

### ISSUE THREAD

**Issue by kmthorsnes** [CraftAcademy/CraftOverflow#6]
After following the guided steps i get the error message as shown in screenshot attached. 
Where have I gone wrong wrong here? 
<img width="1784" alt="skjermbilde 2018-02-06 kl 09 26 07" src="https://user-images.githubusercontent.com/24756550/35848941-309d6544-0b20-11e8-8d8f-79ad6ea4a6ea.png">

**Comment by diraulo** [comment]
@kmthorsnes May I see the content of your `Gemfile` and the `spec_helper.rb`

**Comment by faraznaeem** [comment]
Hi please add some background to the error. What did you try to implement and in what step did you get the error?

**Comment by kmthorsnes** [comment]
@diraulo Sure, 
See screenshots. 
![skjermbilde 2018-02-06 kl 09 32 58](https://user-images.githubusercontent.com/24756550/35849146-e3f70b5e-0b20-11e8-8b06-3ab7b5a257d0.png)
![skjermbilde 2018-02-06 kl 09 33 12](https://user-images.githubusercontent.com/24756550/35849147-e412cd9e-0b20-11e8-8856-b80f31be0c32.png)

@faraznaeem Hi, this was when I tried to run rspec for the first time after setup that this error showed up.

**Comment by diraulo** [comment]
@kmthorsnes 

You should also require the `middleman-deploy` gem in your `spec_helper.rb` file. I should solve this problem. 

Whenever you add a new gem to your `Gemfile`, you also need to require it at the top of the `spec_helper.rb` file or else you might see errors like the one you have above. The current setup doesn't autoload gems in the test environment.

**Comment by diraulo** [comment]
You can also modify the `spec_helper.rb` file as follow to autoload those gems

```ruby
require 'bundler'
require 'rspec'
require 'capybara/rspec'

Bundler.require(:default)

middleman_app = ::Middleman::Application.new

Capybara.app = ::Middleman::Rack.new(middleman_app).to_app do
  ...
end

```

Note that I've removed some of the `require` statements and replaced them with

```ruby
require 'bundler'
...

Bundler.require(:default)
```

Note to @kmthorsnes: Remember to close the issue once it has been resolved 🙂
