### ISSUE TITLE
Haml Syntax..

### ISSUE THREAD

**Issue by holgertidemand** [CraftAcademy/CraftOverflow#7]
How do I make a <p> tag continue on the next line.. 
```
.container 
  %p I'm holger,
     and i need help
```
couldn't get the above syntax to work.

**Comment by holgertidemand** [comment]
```
.container
 %p im holger
 and i fixed my own problem.
```

**Comment by tochman** [comment]
The last formatting in the last comment looks weird to me, tbh

**Comment by holgertidemand** [comment]
Well it works :P

**Comment by holgertidemand** [comment]
Ignore this post. I was right from the beginning.

**Comment by tochman** [comment]
All sorted out. Closing the issue.
